#ifndef _LOBOT_CMDS_H_
#define _LOBOT_CMDS_H_

#define LOBOTSERVO_CMD_MOVE_TIME              1
#define LOBOTSERVO_CMD_MOVE_TIME_READ         2
#define LOBOTSERVO_CMD_MOVE_TIME_WAIT         7
#define LOBOTSERVO_CMD_MOVE_TIME_WAIT_READ    8
#define LOBOTSERVO_CMD_MOVE_START            11
#define LOBOTSERVO_CMD_MOVE_STOP             12
#define LOBOTSERVO_CMD_ID_WRITE              13
#define LOBOTSERVO_CMD_ID_READ               14
#define LOBOTSERVO_CMD_ANGLE_OFFSET_ADJUST   17
#define LOBOTSERVO_CMD_ANGLE_OFFSET          18
#define LOBOTSERVO_CMD_ANGLE_OFFSET_READ     19
#define LOBOTSERVO_CMD_ANGLE_LIMIT           20
#define LOBOTSERVO_CMD_ANGLE_LIMIT_READ      21
#define LOBOTSERVO_CMD_VIN_LIMIT             22
#define LOBOTSERVO_CMD_VIN_LIMIT_READ        23
#define LOBOTSERVO_CMD_TEMP_MAX_LIMIT        24
#define LOBOTSERVO_CMD_TEMP_MAX_LIMIT_READ   25
#define LOBOTSERVO_CMD_TEMP_READ             26
#define LOBOTSERVO_CMD_VIN_READ              27
#define LOBOTSERVO_CMD_POS_READ              28
#define LOBOTSERVO_CMD_OR_MOTOR_MODE         29
#define LOBOTSERVO_CMD_OR_MOTOR_MODE_READ    30
#define LOBOTSERVO_CMD_LOAD_OR_UNLOAD        31
#define LOBOTSERVO_CMD_LOAD_OR_UNLOAD_READ   32
#define LOBOTSERVO_CMD_LED_CTRL              33
#define LOBOTSERVO_CMD_LED_CTRL_READ         34
#define LOBOTSERVO_CMD_LED_ERROR             35
#define LOBOTSERVO_CMD_LED_ERROR_READ        36

#endif
